- README.md
- app/adapter/web/src/component/promos/ExtPromo.scss
- app/adapter/web/src/component/promos/ExtPromo.tsx
Promo banner shows `Type less with s/ .`
Promo banner shows `Get Chrome Extension`
> Edit extension promo text and Chrome Web Store link

- app/adapter/web/public/404.html
1. 404.html has default title
2. 404.html doesn't have favicon
1. Update 404.html title to "Short | Page Not Found"
2. Add favicon to 404.html
> Update title and add favicon to 404 page

- README.md
- frontend/.env.production
Domain names are too long:
- Homepage => https://s.time4hacks.com
- HTTP API => https://http-api-s.time4hacks.com
- GraphQL API => https://graphql-api-s.time4hacks.com
short-d.com is used as the new domain name:
- Homepage => https://short-d.com
- HTTP API => https://api.short-d.com
- GraphQL API => https://gql.short-d.com
> Swap domain name to short-d.com

- docker-compose.yml
Postgres keep restarting after upgrading from v11 to v12.
Postgre is able to start normally
> Fix PostgreSQL version conflict

- k8s/backend-deployment.staging.yaml
`first record does not look like a TLS handshake` error is thrown when trying to fetch keys from key generation service. This implies `short backend` is not able to connect to `key generation service`. `kgs` is accessible through port `443` instead of port `80`.
Short backend is able to connect to key generation service successfully.
> Change kgs port from http to https

- backend/app/adapter/graphql/resolver/mutation.go
- backend/app/usecase/auth/authenticator.go
- backend/app/usecase/auth/authenticator_test.go
- backend/app/usecase/signin/oauth.go
- backend/dep/wire_gen.go
Authenticator is currently accepting and producing user email as unique identifier. However, some oauth providers do not provide user's email to Short backend, especially when users mark their emails as private. All the providers are offering user ID instead.
Authenticator now accepts user struct as the inputs and outputs, leaving flexibility of migrating from email to user ID.
> Replace userEmail with user for authentication logic

- backend/app/adapter/migration/9_change_url_alias_type.sql
Addresses #316.
- Assuming DB migration does not happen live and only at startup, we should not need to lock the table to perform this query
- There is already a frontend check to see whether alias goes 50 or over, so there's no need to handle cases where there's an alias 50 or over in the table (we would want the migration to fail in this case so we can assess why something like this would make it through)
> Add change URL alias migration

- backend/app/usecase/url/urlretriever.go
> Fix go-lint warning (replace Sprintf with Errorf)

- frontend/src/service/Error.service.ts
- frontend/src/service/Url.service.ts
When collecting error codes in Url service error handler, it assumes that a `GraphQlError` object will always contain an `extensions` property and causes frontend to crash when `extensions` is missing.
See https://github.com/graphql/graphql-js/blob/v14.5.8/src/error/GraphQLError.js#L83
Now just unknown error will appear.
> Fix error collecting err codes

- frontend/public/index.html
Twitter card preview fail to render
Twitter card preview renders successfully.
> Fix twitter card meta tags

- frontend/public/index.html
Twitter card contains small image
Twitter card contains large image
> Switch Twitter card preview to large image

- frontend/public/index.html
The is an extra `S` in Twitter card's description
Social media preview titles are not complete sentences.
The extra `S` is removed. 
Update social media preview titles.
> Fix preview message

- backend/app/usecase/repository/url_fake.go
- backend/app/usecase/repository/userurl_fake.go
- backend/app/usecase/url/urlcreator_test.go
URLCreatorPersist did not verify repository data correctness.
URLCreatorPersist checks and makes sure repository data is expected.
> Refactor and clean up unit test

- frontend/src/component/pages/Home.tsx
- frontend/src/component/pages/shared/Header.scss
- frontend/src/component/pages/shared/Header.tsx
Reverts byliuyang/short#349
The sign out button shows up even before user signs in. It fails to be hidden after user signed out.
> Revert "Add sign out button on the header"

- backend/app/usecase/account/linker.go
- backend/app/usecase/account/linker_test.go
External account is mapped to Short's internal account through email. However, some identity provider only reveals user's public email, resulting in sign in failure.
Add account linker to map external account to Short's internal account through user IDs.
> Add account linker

- backend/app/adapter/google/identityprovider.go
Add Google OAuth IdentifyProvider.
In order to support Google sign in, we are mapping user's Google account to user's  Short account through user's email. User email can be retrieved from Google API given OAuth token, which is provided by Google OAuth IdentityProvider.
> Add Google OAuth IdentityProvider

- backend/app/adapter/db/sqltest/time.go
- backend/app/adapter/db/url_test.go
- backend/app/adapter/db/userurl_test.go
`mustParseSQLTime` is located inside `db` package.
`MustParseSQLTime` is located inside `sqltest` package.
> Move MustParseSQLTime to sqltest package

- frontend/src/service/StaticConfigDecision.service.ts
Turn on Google sign in button.
In order to support Google sign in, we are mapping user's Google account to user's Short account through user's email. Turn on Google sign in button allows user to use Google OAuth API to sign in.
> Turn on Google sign in button

- backend/app/adapter/db/time.go
- backend/app/adapter/db/url.go
- backend/app/adapter/db/url_integration_test.go
- backend/app/adapter/db/user.go
- backend/app/adapter/db/user_integration_test.go
The backend crashes when trying to perform short link redirection.
The backend can successfully direct short link to the correct long link.
> Fix nil dereference crashing

- frontend/src/service/Error.service.ts
The original message said "generate _a_ available alias" instead of "generate _an_ available alias" but I ended up further improving the wording. Simple change 🙂
> Improve wording of "aliasNotAvailable" error message

- backend/app/adapter/db/githubsso.go
- backend/app/adapter/db/githubsso_integration_test.go
- backend/app/adapter/db/migration/11_add_uniqueness_to_githubsso_table.sql
Add uniqueness constraints to `github_user_id` and `short_user_id`. 
One Github account should be mapped to only one Short account. Vise versa.
> Implement CreateMapping for GithubSSOSql repository

- frontend/src/component/form/TextField.tsx
- frontend/src/component/pages/Home.tsx
resolves https://github.com/short-d/short/issues/205
Automatically fill in long link when `long_link` query parameter exists. The cursor will automatically focused on alias text field, waiting for the user to provide a custom alias.
> Add query parameter to autofill long link

- backend/app/adapter/facebook/account.go
- backend/app/adapter/facebook/account_integration_test.go
- backend/dep/wire_gen.go
- backend/go.mod
- backend/go.sum
Refactor account module for Facebook OAuth.
Previously, we use a 3rd party package for Facebook Graph API. However, importing the whole package just for retrieving user account information seems unnecessary. This pull request provides a better way of sending http GET request to facebook API to retrieve user information without using 3rd party package.
> Refactor account for Facebook OAuth

- backend/app/adapter/facebook/identityprovider.go
- backend/app/adapter/facebook/identityprovider_integration_test.go
- backend/app/adapter/github/identityprovider_integration_test.go
Refactor IdentityProvider for Facebook OAuth.
Currently our implementation for facebook identityprovider is not well written. By sending http POST  instead of http GET request, we ensure the http request is safer.
> Refactor IdentityProvider for Facebook OAuth

- backend/app/usecase/auth/authenticator.go
- backend/app/usecase/auth/authenticator_test.go
Authenticator treats auth token as valid even though it has empty email.
Authenticator treats auth token as invalid when it has empty email.
> Fix empty email bug

- backend/app/usecase/usecase.go
- backend/app/usecase/usecase_test.go
Github sign in redirection logic is invoking HTTP APIs directly inside [routing](https://github.com/short-d/short/blob/master/backend/app/adapter/routing/handle.go#L57-L65) package. This prevents the sign in logic from being reused for non-HTTP views. It also significantly increased the complexity of `routing` package as more routes being added.
Facebook sign in redirection logic is moved into `usecase` package. Interactions with views are abstracted out through `Presenter` interface.
> Move request Facebook sign in to use case

- backend/app/usecase/usecase.go
- backend/app/usecase/usecase_test.go
Github sign in redirection logic is invoking HTTP APIs directly inside [routing](https://github.com/short-d/short/blob/master/backend/app/adapter/routing/handle.go#L57-L65) package. This prevents the sign in logic from being reused for non-HTTP views. It also significantly increased the complexity of `routing` package as more routes being added.
Google sign in redirection logic is moved into `usecase` package. Interactions with views are abstracted out through `Presenter` interface.
> Move request Google sign in to Usecase

- frontend/package.json
- frontend/yarn.lock
`react-debounce-input` is missing from `package.json`. This breaks our frontend build.
`react-debounce-input` is added to `package.json`.
> Fix the missed dependency

- backend/app/adapter/facebook/account.go
- backend/app/adapter/facebook/account_integration_test.go
- backend/app/adapter/github/identityprovider_integration_test.go
Didn't obtain user ID after he or she signed in through facebook account. 
Retrieves user ID after he or she signed in through facebook account.
fixes #541
> Support retrieving user ID from Facebook account

- frontend/src/component/pages/Home.scss
- frontend/src/component/pages/Home.tsx
- frontend/src/component/pages/shared/CreateShortLinkSection.scss
- frontend/src/component/pages/shared/CreateShortLinkSection.tsx
- frontend/src/component/pages/shared/Footer.tsx
The current create short link component is nested inside home page. It's very difficult to read and understand. 
Extracted created short link section into its own component. It is much cleaner and easier to understand the structure of the homepage.
> Create short link refactor

- frontend/src/component/pages/Home.tsx
The following error occurs when the user try to use autofill long link feature 
The bug is fixed
> Fix autofill long link bug

- backend/app/adapter/db/url_integration_test.go
- backend/scripts/format
`goimports` does not support `-s` ( simplify ) option.
Add gofmt to code formatters because it supports `-s` option.
> Add gofmt to code formatters

- CONTRIBUTING.md
There is no clear instruction on how our weekly standups are organized. It's difficult to plan the works and track executions without reinforcing weekly standups.
Included instructions and requirements for contributors to join our weekly standups.
> Add instruction for weekly standups to contributing.md

- frontend/src/component/pages/Home.tsx
- frontend/src/component/pages/shared/CreateShortLinkSection.tsx
- frontend/src/component/pages/shared/ShortLinkUsage.tsx
- frontend/src/entity/Url.tsx
- frontend/src/service/Url.service.ts
When createdUrl object is fetched from GraphQL API, the originalUrl field is named as 'originalURL' due to Golang's convention, which makes displaying the original URL in the UI impossible. The user will see the following when they create a short link.
Fixed the createdUrl object by creating a new type as the receiver of GraphQL response, which gets converted to the properly named createdUrl object (with the field 'originalUrl' rather than 'originalURL') for JavaScript to process. Now the user is able to see the original URL in the UI after they've created a short link.
> Fix short link usage original URL display bug

- backend/app/adapter/graphql/resolver/authquery_test.go
- backend/app/adapter/graphql/resolver/query_test.go
- backend/app/usecase/auth/payload/email.go
- backend/app/usecase/auth/payload/email_test.go
- backend/app/usecase/auth/payload/factory.go
- backend/app/usecase/auth/payload/payload.go
- backend/app/usecase/auth/payloadtest/factory_stub.go
- backend/app/usecase/auth/payloadtest/payload_stub.go
Authenticator is hardcoded to use email as default unique ID. The email payload validation logic is nested inside authenticator, making it difficult to switch to userID for only some cases.
Decouple and encapsulated all email payload logics into `payload.Email`.
> Add Email payload

- frontend/src/component/ui/Table.scss
Change thead to th for table header CSS selector
- The table header's background is not re-rendered when `thead` CSS selector is used.
- Changing the selector to `th` fixes the issue.
> Fix table header not filling background with change in header width

- frontend/src/service/Captcha.service.ts
- frontend/src/service/Error.service.ts
- frontend/src/service/Url.service.ts
Unknown error is shown when developers forgot to configure reCaptcha site key during local development. This cause lots of confusion for devs It's waste of time to debug this issue during development.
Change the title of invalid reCaptcha site key error to `Invalid ReCaptcha Site key`.
> Add meaningful error message for invalid recaptcha site key

- backend/app/adapter/graphql/resolver/authmutation.go
- backend/app/adapter/graphql/resolver/authquery.go
- backend/app/adapter/graphql/resolver/authquery_test.go
- backend/app/adapter/graphql/resolver/error.go
- backend/app/adapter/graphql/resolver/mutation.go
- backend/app/adapter/graphql/resolver/query.go
- backend/app/adapter/graphql/resolver/query_test.go
- backend/app/adapter/graphql/resolver/viewer.go
- frontend/src/component/pages/Home.tsx
- frontend/src/service/Captcha.service.ts
- frontend/src/service/Error.service.ts
- frontend/src/service/Url.service.ts
Part of fix for #623.
Users were promoted with `unknown error` after their authentication token expired. Frustrated users have no clue how to fix this error and cannot create new short links.
Users are now promoted to sign in after their auth token expired.
> Promote sign in after auth token expired

- backend/dep/wire.go
- backend/dep/wire_gen.go
Part of #623
Auth token expires every 24 hours. This forces users to repeatedly sign in everyday and is annoying user experience.
Extend auth token valid duration from a day to a week.
> Extend auth token valid duration from a day to a week

- frontend/src/component/ui/PageControl.tsx
Fixes #661 
The pageControl had the responsibility of fetching the initial data.
Moving the responsibility of fetching the initial data to it's parent as in some cases, the pageControl would not be even required to be mounted or rendered if no initial data exists.
> Refrain PageControl mount from triggering onPageChanged event

- frontend/src/component/ui/Toast.spec.tsx
Fixes #663 
One of the tests didn't have `ckearAllTimers` which made the Toast component to call `hide` after the component was unmounted from the test.
Also, added `clearAllTimers` in `afterEach` method to remove non test related(AAA) code in each tests.
> Fix memory leak warning in toast unit tests

- frontend/src/component/pages/Home.scss
- frontend/src/component/pages/Home.tsx
- frontend/src/component/pages/shared/UserShortLinksSection.scss
- frontend/src/component/pages/shared/UserShortLinksSection.spec.tsx
- frontend/src/component/pages/shared/UserShortLinksSection.tsx
- frontend/src/component/ui/Table.scss
> Retyle user short links section

- frontend/src/component/pages/shared/UserShortLinksSection.scss
- frontend/src/component/pages/shared/UserShortLinksSection.tsx
When original url is too long, it stretches the table row and causes scrollbar to show up.
Long links are broken into multiple lines.
> Break long link into multiple lines

- backend/app/usecase/instrumentation/instrumentation.go
Segment API throws empty user ID error. Segment stopped tracking user interactions. This is caused by ineffectively mutating ctx.
Segment is now anonymously tracking user actions again.
> Fix empty user ID for instrumentation

- backend/dep/provider/entryrepo.go
- backend/dep/wire.go
- backend/dep/wire_gen.go
- backend/env/env.go
Developers are confused when they didn't see logs in the terminal during local development. Also, logging to DataDog has network latency.
Switch to local logger when developing in local env.
> Support switching to local logger under dev environment

- backend/app/usecase/instrumentation/instrumentation.go
Some of the instrumentation tracking code was never invoked. `featureToggleRetrievalFailed` needs to be invoked before `madeFeatureDecision`.
`featureToggleRetrievalFailed` and `madeFeatureDecision` can be invoked independently.
> Switch from blocking to parallel

- backend/app/adapter/routing/handle.go
- backend/app/usecase/instrumentation/instrumentation.go
We are running out of monthly free users on Segment. This is because each request is treated a independent user.
All anonymous users share the same user ID from now on. We also track the short link they visiting to potential monitor phishing attacks and to determine the hotspots in the short links.
> Replace ID of anonymous user with hard-coded value

- backend/app/adapter/google/safebrowsing.go
`path.Clean` prevents Google Safe Browsing API from working.
Remove `path.Clean`. Safe Browsing API now works again.
> Fix malicious URL detection bug

- frontend/src/component/ui/Navigation.scss
- frontend/src/component/ui/Navigation.spec.tsx
- frontend/src/component/ui/Navigation.tsx
Part of #612 
Add navigation component containing menu items
> Add navigation component

- frontend/src/component/ui/Drawer.scss
- frontend/src/component/ui/Drawer.spec.tsx
- frontend/src/component/ui/Drawer.tsx
Part of #612
Add a drawer component whose children will consist of the ReactElements which the drawer is going to contain.
> Add drawer component

- frontend/package.json
- frontend/yarn.lock
PRs #717 and #735 contain errors when running the script formatter due to use of optional chaining. Upgrading `prettier` to latest version fixes this. https://github.com/prettier/prettier/issues/7088
> Upgrade prettier to 1.19.1

- backend/app/usecase/url/urlcreator.go
- backend/app/usecase/url/urlcreator_test.go
- frontend/src/service/Url.service.ts
Fixes blank alias portion of #728. Currently just addresses empty aliases, TBD if malicious input for alias should also be handled. (edit: Will address in #744 to reduce scope of this PR)
Adding short link with alias set to empty string (not possible from frontend but GraphQL request can be crafted to have alias be set to empty string) will create entry with alias set to empty string.
See #728.
Now generates a random alias whenever empty string alias is passed. It should now be impossible to have a short link with alias of empty string.
> Generate random alias if empty alias provided

- frontend/src/component/ui/Tabs.spec.tsx
- frontend/src/component/ui/Tabs.tsx
Part of #612 
Add Tabs component which can be handy when there a set of pages of which one should be shown at a time and rendering should be controlled with the index of the pages.
> Add tabs component

- frontend/src/component/ui/Navigation.scss
Part of #612 
The menu didn't have any spacing between the items and the border of the component.
Added padding and margins to make spaces between the menu items and the parent component.
> Refactor Navigation Menu Items spacing

- backend/app/adapter/facebook/identityprovider.go
- backend/app/adapter/facebook/identityprovider_integration_test.go
- backend/app/adapter/github/identityprovider.go
- backend/app/adapter/google/identityprovider.go
- backend/app/adapter/google/identityprovider_integration_test.go
Redundant request body is added even though the data is already included in query parameters.
Remove unnecessary request body.
> Clean up Google & Facebook identify providers

- backend/app/adapter/sqldb/user.go
- backend/app/adapter/sqldb/user_integration_test.go
- backend/app/usecase/repository/user.go
- backend/app/usecase/repository/user_fake.go
- backend/app/usecase/sso/linker.go
- backend/app/usecase/sso/linker_test.go
Existing accounts have no user ID. This results in external account being mapped to empty ID during linking and hence repeated sign in.
Auto generate ID for existing accounts with empty ID during account linking.
> Auto generate ID for existing accounts during account linking

- backend/app/usecase/feature/static.go
- frontend/src/component/UIFactory.tsx
- frontend/src/component/pages/shared/CreateShortLinkSection.scss
- frontend/src/component/pages/shared/CreateShortLinkSection.tsx
- frontend/src/component/pages/shared/PreferenceTogglesSubSection.scss
- frontend/src/component/pages/shared/PreferenceTogglesSubSection.tsx
- frontend/src/service/feature-decision/DynamicDecision.service.ts
- frontend/src/service/feature-decision/FeatureDecision.service.ts
Divider for preference toggles show up even when there is no toggle.
Extract preference toggles into a separate subsection section so that we can dynamically hide it when there is no toggle enabled.
> Extract preference toggles into a separate subsection

- backend/app/usecase/changelog/changelog.go
- backend/app/usecase/changelog/changelog_test.go
Server time may not be in UTC and therefore when new change is created released_at may not be in UTC as well. In order to maintain same time irrespective of server location we should use enforce UTC time
> Use UTC time when creating new Change

- frontend/public/index.html
Canonical meta tag prevents use of custom og:tags for social media sharing on LinkedIn/Facebook/Twitter.
> Remove canonical meta tag from index.html

- frontend/package.json
- frontend/src/service/HTTP.service.ts
- frontend/src/service/ShortHTTP.api.ts
- frontend/yarn.lock
HTTP get client by default tries to parse response into JSON. However, some HTTP requests do not have response.
Separate JSON parsing from `get` method into `getJSON`.
> Fix http error

- frontend/src/component/UIFactory.tsx
- frontend/src/component/hoc/withFeatureToggle.tsx
Part of #612 
Implementation for `withFeatureToggle` lies within `UIFactory`. With more higher order components getting into the project, it's better we separate the building HOC logic in a separate file and focus only on building UI components in `UIFactory`
Created a new directory called `hoc` inside `components` and added `withFeatureToogle` there.
> Separate out withFeatureToggle HOC component

- frontend/src/component/hoc/withPageAuth.tsx
Part of #612 
Add `withPageAuth` HOC to wrap auth protected pages. It currently returns a 404 page when the user isn't authorized to view the page and displays the wrapped page if authorized.
> Add Auth HOC to wrap authorized pages

- frontend/src/component/UIFactory.tsx
- frontend/src/component/hoc/withFeatureToggle.tsx
- frontend/src/component/hoc/withPageAuth.tsx
- frontend/src/service/feature-decision/DynamicDecision.service.ts
Part of #612 
The feature toggle and auth toggle decision is currently being made in constructor of UIFactory making it happen only once during the initial setup unless the page is reloaded. With the current dynamic(auth based) feature toggle functionality in place, this won't work as users will keep alternating between logged in and out state. That is, when a user is initially logged out, the permission based features will be unavailable and it will continue to be unavailable even after logging in.
Instead of passing the decision(`Promise<bool>`) in the `withFeatureToggle` and `withPageAuth` HOCs, we pass the decision maker so that it can be called while mounting the component and thus satisfying the dynamicity.
> Make feature toggle decision at mount time instead of build time

- .drone.yml
Code coverage used to report `failed to find commit` error when we can to force push to master to critical fixes. This forced us to replace Codecov token every time when it happens in order to continuously report code coverage. Forcing report coverage on master alleviated this issue. 
Codecov is now much stable. Hence removing this unnecessary reporting to speed up CI build.
> Remove redundant code coverage after merged to master branch

- .drone.yml
- backend/app/usecase/search/order/created_time.go
- backend/app/usecase/search/order/created_time_test.go
- backend/app/usecase/search/order/order.go
- backend/app/usecase/search/order/unchanged_test.go
The result from the search doesn't have any order option other than Unchanged which is the default option.
Add ByCreatedTimeASC option, which sorts the result of the searchable resources based on created time in ascending order. 
Sorry for this rather larger PR, most of it is test cases. Besides the unit test for ByCreatedTimeASC order, in this PR I included the unit tests for Unchanged order which consists of the same test cases, but we can discuss if those tests are not meaningful for Unchanged order.
> Add ByCreatedTimeASC order for Search

- backend/app/adapter/sqldb/short_link.go
- backend/app/adapter/sqldb/short_link_integration_test.go
Part of #809 
UpdateOGMetaTags sqldb adapter method returns new ShortLink after updating OpenGraph MetaTags.
A corresponding GraphQL mutation API will be created for updating OpenGraph MetaTags for a ShortLink
> Add UpdateOpenGraphMetaTags to adapter

- backend/app/adapter/sqldb/user_short_link.go
- backend/app/adapter/sqldb/user_short_link_integration_test.go
* Add ability to check if an alias exists within the user's short link repo.
* Add integration tests to cover FindAliasByUser
This is the first PR related to #798. It updates the sql adapter so that it can verify if a specific alias is owned by a given user.
> Add HasMapping to sql adapter

- .drone.yml
Codecov fails to find the coverage for some commits on master branch. This results in coverage for future commits never get reported. Revert this PR to fix the issue.
Reverts short-d/short#839
> Revert "Remove redundant code coverage after merged to master branch"

- backend/app/adapter/recaptcha/recaptcha.go
- backend/app/adapter/recaptcha/recaptcha_integration_test.go
Fixes #739.
Also added a test case for recaptcha error response. This pathway shouldn't normally happen since reCAPTCHA always returns 200 response even when there's an error, but this test case should now increase coverage of recaptcha module from 90% to 100%.
> Remove manual string concatenation for reCaptcha API request body

- backend/app/adapter/routing/handle.go
- backend/app/adapter/routing/route.go
Back when we had our url package(github.com/short-d/short/backend/app/usecase/url) it collided with net/url package. To avoid collision net/url was renamed to netURL.
We should avoid renaming imports except to avoid a name collision and that's why now the netURL doesn't need renaming.
> Remove renaming of net/url package

- backend/app/usecase/search/search.go
- backend/app/usecase/search/search_test.go
If we search more than the one resource, it only searches the last resource which creates a concurrency bug. The bug is present because of the overwritten value of the current resource inside the for loop when a new thread is started. This PR fixes this issue.
> Fix bug for concurrent search of resources  

- backend/app/adapter/gqlapi/schema.go
- frontend/src/component/ui/Icon.tsx
- frontend/src/service/shortGraphQL/ShortLinkGraphQL.api.ts
- frontend/src/service/shortGraphQL/schema.ts
The is no documentation for GraphQL APIs. Both internal & external developers are confused how to use them.
Add description to the API and the arguments.
> Add documentation for GraphQL apis

- frontend/src/component/ui/ChangeLogModal.scss
Fixes #857.
"View All Updates" button in changelog is not vertically aligned.
After some digging, it appears this is due to flexbox layout and a missing property to align it vertically (on cross-axis)
Using [align-items](https://css-tricks.com/almanac/properties/a/align-items/) CSS property, the flexbox item is appropriately aligned in the cross-axis.
> Center align changelog 'view all updates' button

- frontend/src/service/Captcha.service.ts
- frontend/src/service/ChangeLog.service.ts
- frontend/src/service/shortGraphQL/ChangeLogGraphQL.api.ts
- frontend/src/service/shortGraphQL/schema.ts
Part of #612 
Add client side service methods for deleting a change in admin panel.
> Add delete client services

- frontend/src/component/ui/Section.scss
- frontend/src/component/ui/Section.spec.tsx
- frontend/src/component/ui/Section.tsx
Section doesn't support options. However, editing short link section needs an option to make the region editable.
Support adding options to Section.
> Support having options in Section

- backend/app/adapter/gqlapi/api_test.go
- backend/app/usecase/shortlink/updater.go
- backend/app/usecase/shortlink/updater_test.go
When a user tries to update a short link but the updated short link alias already exists then it fails because of the Postgres database unique on the alias.
Handle error in Usecase, which is independent of storage and more friendly. Before pushing the commit, I ran the format script, which added some changes.
> Handle duplicated alias in Usecase

- backend/app/adapter/gqlapi/resolver/authmutation.go
- backend/app/usecase/changelog/changelog.go
- backend/app/usecase/shortlink/updater_test.go
Changed the convention of error type checking to use the new style introduced in Go 1.13, addressing #823.
https://blog.golang.org/go1.13-errors
One of the major benefits of using this style is that `errors.As` (and `errors.Is`) will examine the entire error chain and give you the error if it's within the chain. A drawback is that the syntax looks a bit more verbose than switch statements, but the ability to examine the error chain makes up for it I think!
> Refactor error type checking to use errors.As

- frontend/src/component/ui/Button.module.scss
- frontend/src/component/ui/Button.tsx
Currently, the button component can be accidentally styled in it's parent when css selectors overlap. This results in confusion and unnecessary debugging when things start to break.
Switch to css module so that the styles of the button is complete isolated from it's consumers.
> Migrate to CSS module to avoid style leaking

- frontend/src/component/pages/shared/sign-in/FacebookSignInButton.tsx
- frontend/src/component/pages/shared/sign-in/GithubSignInButton.tsx
- frontend/src/component/pages/shared/sign-in/GoogleSignInButton.tsx
- frontend/src/component/pages/shared/sign-in/SignInButton.scss
- frontend/src/component/pages/shared/sign-in/SignInButton.tsx
- frontend/src/component/ui/Button.module.scss
- frontend/src/component/ui/Button.tsx
- frontend/src/component/ui/styling.ts
Sign in button in the sign in modal and the signout button in the header have their own implementation of button. The only difference between them is the look and feel.
Allow users to pass styles property in order to customize the button visual appearance of the button. This allows multiple place to use the button while they have different look and feel.
> Support styling for button

- .drone.yml
Docker image for storybook was never tagged for pushing to Dockerhub.
Tagged storybook image with the correct name.
> Fix Docker image name

- story/src/1-Toggle.stories.tsx
Adds a section in the storybook for `Toggle` component.
> Add storybook for Toggle

- frontend/src/component/pages/shared/CreateShortLinkSection.tsx
The confirmation message doesn't show the long link for which the short link was created.
Added the created long link into states which is displayed in the confirmation message
> Fix bug not showing created long link

- frontend/src/component/ui/Table.tsx
There is no way when using the table component to change the size of the headers or aligning the items inside the table from the parent component. These two functionalities are highly required and we should support this basic customization in a table.
Added support to customize header font size and aligning both header and body data.
> Extend Table component to support resizing and aligning items

- frontend/src/service/Url.service.ts
Port info is missing in the generated frontend link due to which the link is not correct when the port is other than port 80.
Added port info in the generated frontend link.
> Added missing port info in the frontend link.

- story/src/0-Button.stories.tsx
Split from #988. Updates Button's storybook to add a green style that was in its SCSS module but not previously included in its storybook.
> Add green Button to storybook

- backend/app/adapter/gqlapi/resolver/query_test.go
- backend/app/adapter/sqldb/changelog_integration_test.go
- backend/app/usecase/changelog/changelog_test.go
- backend/app/usecase/shortlink/metatag_test.go
Fixes #959. Use `ptr.String()` to allow for direct embedding of strings into tests.
> Use ptr.String for test cases that contain strings

- story/src/2-Icon.stories.tsx
Unfortunately missed this from my review of #1002. I removed `addon-info` in PR #996 because it's now deprecated, and because of this change, the Icon story failed once it merged to `master`. This PR removes `addon-info` from the story and also did a bit of auto-formatting.
> Remove addon-info from Icon story
