short-d/short

- app/adapter/migration/1_create_url_table.sql
- app/adapter/migration/2_create_user_table.sql
- app/adapter/migration/4_rename_user_table_and_columns.sql
> Update SQL migrations

- app/adapter/graphql/resolver/error.go
- app/adapter/web/.env.development
- app/adapter/web/.env.production
- app/adapter/web/.env.test
- app/adapter/web/package.json
- app/adapter/web/src/component/App.tsx
- app/adapter/web/src/component/SignIn.tsx
- app/adapter/web/src/service/Auth.service.ts
- app/adapter/web/src/service/Cookie.service.ts
- app/adapter/web/src/service/Url.service.ts
- app/adapter/web/yarn.lock
User can't create short URL after JWT token expired.
Show user sign in popup if their JWT token expired.
> Introduce force sign in

- bin/build-web-dev
Unnecessary environmental variables are added in build-web-dev script. Those environmental variables are already included in app/adapter/web/.env.development
Unnecessary environmental variables are added in build-web-dev script.
> Clean up web dev script

- README.md
- app/adapter/web/.yarnclean
- app/adapter/web/package.json
- app/adapter/web/src/component/App.tsx
- app/adapter/web/src/index.scss
- app/adapter/web/src/index.tsx
- app/adapter/web/yarn.lock
- modern/mdhttp/server.go
> Revert "Graphql playground"

- dep/wire.go
- dep/wire_gen.go
> Group providers into sets

- cmd/cmd.go
- dep/wire.go
- dep/wire_gen.go
- go.mod
- go.sum
> Move cobra out of Short

- .drone.yml
> Revert "Switch back to dockerhub"

- README.md
An extra line of command is mistakenly added to start Docker portion of the README
The incorrect command is removed from README
> Fix misspelling in README file

- .drone.yml
Unit tests are not running when opening a pull request
Unit tests is running when opening a pull request
> Enable unit test for pull requests

- README.md
There is no link of the tools that our developers use
Link of the tools are added to README
> Add tools section to README

- app/usecase/url/urlcreator_fake_test.go
- app/usecase/url/urlretriever_fake_test.go
Issue-id: #197
Signed-off-by: Kamalashree N <nagaraj.kamalashree@gmail.com>
Improve test-coverage for `app/usecase/url` package.
> Add tests for fake URL creator and retriever

- .drone.yml
Code coverage was disabled for pull requests
Enable coverage for pull requests
> Enable code coverage for pull request

- .drone.yml
Tests are running when pushing a new commit to any branch.
Tests running only when the branch has an open PR.
> Update .drone.yml to only run tests when there is an open PR

- README.md
- frontend/scripts/build
Original README has outdated instructions of setting up the environment.
Setting up the environment instructions is consistent with the latest code refactor.
> Update and clean up setup instructions

- .dockerignore
- Dockerfile-build
- Dockerfile-coverage
- README.md
> Revise generate static assets process

- backend/app/adapter/migration/6_add_user_id_column.sql
- backend/app/adapter/migration/7_create_github_oauth_user_relation_table.sql
This is a incremental change to fix #192
> Add user id db column and github_oauth_user_relation table

- frontend/src/service/Url.service.ts
Nothing is shown on the UI when alias is successfully created.
UI is showing the created alias.
> Fix UI no response bug

- k8s/frontend-ingress.staging.yaml
- k8s/frontend-pod.staging.yaml
- k8s/frontend-service.staging.yaml
Web UI shows up when visiting https://staging.short-d.com
> Add frontend k8s configs for staging env

- frontend/src/component/App.tsx
- frontend/src/component/pages/Home.tsx
- frontend/src/service/Url.service.ts
Frontend redirects short link back to itself and forms infinite loop.
Frontend redirects short link to backend.
> Fix infinite redirect

- frontend/public/index.html
SEO metadata uses https://s.time4hacks.com as home page.
SEO metadata uses https://short-d.com as home page.
> Update SEO metadata

- frontend/src/component/UIFactory.tsx
- frontend/src/service/FeatureDecision.service.ts
- frontend/src/service/StaticConfigDecision.service.ts
#192 
Temporarily disable Github sign in
> Disable Github sign in

- backend/app/entity/ssouser.go
- backend/app/usecase/service/identityprovider.go
- backend/app/usecase/service/identityprovider_fake.go
- backend/app/usecase/service/ssoaccount.go
- backend/app/usecase/service/ssoaccount_fake.go
- backend/app/usecase/sso/sso.go
- backend/app/usecase/sso/sso_test.go
Short is using oauth as it's default authentication method.
Generalize oauth to single sign on.
> Add SingleSignOn use case

- backend/app/usecase/repo/user_fake.go
It's hard to test use cases that dependent on user repository due to lack of fake repo implementation.
Add fake user repo to easy testing.
> Add fake user repository

- backend/app/adapter/db/table/user.go
- backend/app/adapter/db/user.go
- backend/app/adapter/db/user_test.go
- backend/app/usecase/repo/user.go
- backend/app/usecase/repo/user_fake.go
`UserID` can now be assigned to existing account given user `email`.
> Add UpdateUserID to user repository

- backend/app/adapter/graphql/graphql_test.go
- backend/app/usecase/input/validator.go
- backend/app/usecase/url/urlcreator.go
- backend/app/usecase/url/urlcreator_test.go
- backend/app/usecase/validator/alias.go
- backend/app/usecase/validator/alias_test.go
- backend/app/usecase/validator/longlink.go
- backend/app/usecase/validator/longlink_test.go
- backend/dep/wire.go
- backend/dep/wire_gen.go
> Rename input to validator and remove Validator interface

- frontend/public/index.html
Google search title does not match social media preview title
Google search title does not matches social media preview title
> Update Google search title

- README.md
Add code review guideline in order to provide a better developer experience.
> Add code review guideline to README

- .gitignore
- backend/app/adapter/db/user_test.go
- backend/app/adapter/db/userurl.go
- backend/app/adapter/db/userurl_test.go
- backend/app/usecase/repository/userurl.go
- backend/app/usecase/repository/userurl_fake.go
- backend/app/usecase/url/urlcreator_test.go
Add `FindAllAliasesByUser` to `UserURLRelation` repository.
> Add FindAliasesByUser to UserURLRelation repository

- README.md
> Add testing section to README

- backend/app/usecase/repository/user_fake.go
1) Fake user repository doesn't have a way to check whether an user with given ID exists. 
2) User ID is not properly updated when invoking UpdateUserID method.
1) Add IsUserIDExist to UserFake
2) Fix UpdateUserID bug
> Add IsUserIDExist to UserFake and fix UpdateUserID bug

- backend/app/usecase/repository/accountmapping.go
- backend/app/usecase/repository/accountmapping_fake.go
Add account mapping repository interface and fake implementation.
> Add account mapping repository

- backend/app/adapter/db/url.go
> fix(error): return error instead of nil

- README.md
> Fix app link in README

- backend/main.go
Add Google sign in configurations from environment variables
> Read Google sign in configurations from environment variables

- backend/app/adapter/google/account.go
- backend/app/adapter/google/identityprovider.go
The App cannot obtain user's email and ID from Google API.
The App is able to retrieve user's email and ID from Google API.
> Fix google sign in

- backend/app/adapter/github/account_integration_test.go
> Fix build flag for Github account integration test

- backend/app/adapter/google/account_integration_test.go
- backend/go.sum
> Add gateway integration test for Google account API

- README.md
> Fix Google sign in screenshot not correctly displayed in the README

- .github/CODEOWNERS
@byliuyang  has to review all the PRs. This takes significant amount of time, hampering @byliuyang 's feature delivery speed.
Even though @byliuyang has good understand of Go, he is not quite an expert of language internals yet.
Add @alldroll, an expert of Go, as the code owner for Go programming language, offering him opportunities to practice communication and to level up the team's Go skills.
Well, I want to be honest with all of you, having an extra code reviewer will also make my life easier. So that I can focus on driving projects.
> Add Alexander as code owner for Go language

- backend/app/adapter/google/identityprovider_integration_test.go
- backend/app/usecase/presenter.go
> Add integration test for google OAuth IdentityProvider

- backend/app/adapter/github/identityprovider_integration_test.go
> Add integration test for Github OAuth IdentityProvider

- frontend/src/component/pages/Home.tsx
- frontend/src/component/pages/shared/Header.scss
- frontend/src/component/pages/shared/Header.tsx
- frontend/src/component/ui/Button.tsx
Added sign out button to header
> Add sign out button

- frontend/src/dep.ts
- frontend/src/service/Search.service.ts
There are unused variables in SearchService. 
The unused variables are removed. They will be added back when the real implementation is provided.
> Remove unused code

- backend/app/usecase/account/linker_test.go
> Fixed malformatted code

- frontend/package.json
- frontend/src/component/styles/center.scss
- frontend/src/component/styles/color.scss
- frontend/src/component/styles/scrollbar.scss
- frontend/src/component/ui/ChangeLogModal.scss
- frontend/src/component/ui/ChangeLogModal.tsx
- frontend/src/component/ui/Modal.scss
- frontend/src/entity/Update.tsx
- frontend/yarn.lock
> Add ChangeLogModal

- .drone.yml
- frontend/.env.production
- frontend/.env.staging
- frontend/.env.test
- frontend/package.json
- frontend/src/component/UIFactory.tsx
- frontend/src/component/pages/Home.tsx
- frontend/src/dep.ts
- frontend/src/service/extensionService/BrowserExtension.factory.ts
- frontend/src/service/extensionService/BrowserExtension.service.ts
- frontend/src/service/extensionService/ChromeExtension.service.ts
- frontend/src/service/extensionService/DefaultExtension.service.ts
- frontend/yarn.lock
Fixes #545 
- Handles the exception when extension_id provided is invalid.
- Refactor extension service classes.
> Invalid extension_id error in dev and staging phase

- frontend/src/component/pages/Home.tsx
> Fix autofill long link bug (#557)

- backend/app/adapter/db/user.go
- backend/app/adapter/db/user_integration_test.go
- backend/app/usecase/repository/user.go
- backend/app/usecase/repository/user_fake.go
Add GetUserByID to User repository.
> Add GetUserByID to User repo

- frontend/package.json
- frontend/src/component/ui/Button.spec.tsx
- frontend/yarn.lock
> Add unit tests for Button

- frontend/src/component/ui/Section.spec.tsx
> Add unit tests for Section

- frontend/src/component/ui/Notice.spec.tsx
> Add unit tests for Notice

- frontend/src/component/pages/Home.tsx
- frontend/src/component/ui/Modal.scss
- frontend/src/component/ui/Modal.spec.tsx
- frontend/src/component/ui/Modal.tsx
> Fix modal keep showing up bug

- frontend/scripts/test
There is clear instruction on how to run automated test for the frontend
Add `scripts/test` to provide intuitive way to run frontend tests
> Add test script for frontend

- frontend/src/component/ui/Table.spec.tsx
Fixes #619 
Renamed toastRef to tableRef in table unit tests
> Rename toastRef to tableRef in table unit tests

- frontend/src/component/ui/Button.scss
- frontend/src/component/ui/Button.tsx
- CSS properties for the Button component is generalized to all HTML buttons. This causes styles to leak into other components that have their own internal buttons. 
- Add a class to Button component so that it doesn't interfere other forms of custom buttons.
> Fix styling leaking issue for Button component

- backend/app/adapter/db/url.go
- backend/app/adapter/graphql/graphql_test.go
- backend/app/adapter/graphql/resolver/authquery_test.go
- backend/app/adapter/graphql/resolver/query_test.go
- backend/app/usecase/repository/url_fake.go
- backend/app/usecase/url/urlretriever.go
- backend/app/usecase/url/urlretriever_test.go
- backend/dep/wire.go
- backend/dep/wire_gen.go
> Add GetURLs method to url usecase 

- backend/app/usecase/url/urlretriever_test.go
> Fix test cases referencing incorrect variable when running

- frontend/src/component/UIFactory.tsx
- frontend/src/component/pages/Home.tsx
- frontend/src/dep.ts
`CaptchaService` passed into Home page component as a property but never used.
Remove the unused `CaptchaService` from Home page component.
> Remove unused captcha service from Home page component

- backend/app/usecase/url/urlretriever.go
- backend/app/usecase/url/urlretriever_test.go
- backend/dep/wire_gen.go
> Rename GetURLs to GetURLsByUser in url usecase

- backend/app/adapter/graphql/resolver/authquery.go
- backend/app/adapter/graphql/schema.go
> Add GraphQL API to show URLs created by current user

- backend/unit/unit.go
- backend/unit/unit_test.go
Have a central place to parse units.
> Create unit package

- README.md
- backend/.env.dist
- backend/app/adapter/instrumentation/factory.go
- backend/app/adapter/instrumentation/instrumentation.go
- backend/app/adapter/routing/handle.go
- backend/app/app.go
- backend/app/usecase/observability/obervability.go
- backend/cmd/cmd.go
- backend/dep/provider/ipstack.go
- backend/dep/provider/segment.go
- backend/dep/wire.go
- backend/dep/wire_gen.go
- backend/go.mod
- backend/go.sum
- backend/main.go
There is no way to track how user interact with Short apis. Without that data, the engineer team has no clue how to improve our system.
There is also no way to track which regions do the users come from. Hence, the engineers are not sure whether we should add global load balancer to improve system performance. 
Integrate [Segment](https://segment.com) and [IPStack](https://ipstack.com/) to anonymously track user actions and coarse geo location.
Note: User IDs in the graph is randomly generated. That's why it's anonymous.
> Track interaction and coarse geo location of the anonymous user

- .github/CODEOWNERS
Harry is starting job search now. Will temporarily focus on coding interview preparation.
Moving forwards:
- @arberiii will be the code owner for Go.  
- @rohithbalaji123 will be code owner for frontend.
They will also drive code quality and lead feature development.
> Add arberiii and rohithbalaji123 as code owners

- backend/app/adapter/graphql/resolver/authquery.go
- backend/app/usecase/changelog/changelog.go
> Return authentication error in change log API

- frontend/src/dep.ts
- frontend/src/service/cache/cache.ts
- frontend/src/service/cache/in-memory.cache.ts
- frontend/src/service/feature-decision/DynamicDecision.service.ts
The UI flashes when the user is typing in the text field. This delay is caused by unnecessarily fetching feature toggle value during every rendering event. 
The UI only flashes when the first the page loads.
> Cache feature toggle response in the memory 

- frontend/src/component/UIFactory.tsx
- frontend/src/component/pages/Home.tsx
- frontend/src/dep.ts
- frontend/src/service/ShortGraphQL.api.ts
- frontend/src/service/ShortLink.service.ts
- frontend/src/service/feature-decision/DynamicDecision.service.ts
- frontend/src/service/feature-decision/FeatureDecision.service.ts
- frontend/src/state/actions.ts
- frontend/src/state/reducers.ts
Part of #193 
Integrate user short link section with necessary services into Home page component.
> Integrate user short links section into home page

- backend/app/adapter/routing/handle.go
- backend/app/adapter/routing/route.go
- backend/app/usecase/feature/decision.go
- backend/app/usecase/feature/dynamic.go
- backend/app/usecase/feature/dynamic_test.go
- backend/app/usecase/feature/static.go
- backend/dep/provider/feature.go
- backend/dep/provider/routes.go
- backend/dep/wire.go
- backend/dep/wire_gen.go
> Add static deature decision maker

- frontend/src/service/Error.service.ts
> Show error for malicious content input

- backend/app/adapter/graphql/graphql_test.go
- backend/app/usecase/url/urlcreator.go
- backend/app/usecase/url/urlcreator_test.go
- backend/dep/wire_gen.go
> Track when a short link is created

- backend/.env.dist
- backend/app/adapter/google/safebrowsing.go
- backend/app/adapter/graphql/graphql_test.go
- backend/app/adapter/graphql/resolver/authmutation.go
- backend/app/adapter/graphql/resolver/error.go
- backend/app/app.go
- backend/app/usecase/risk/blacklist.go
- backend/app/usecase/risk/blacklist_fake.go
- backend/app/usecase/risk/risk.go
- backend/app/usecase/url/urlcreator.go
- backend/app/usecase/url/urlcreator_test.go
- backend/dep/provider/google.go
- backend/dep/wire.go
- backend/dep/wire_gen.go
- backend/main.go
* Change `risk.URLBlackList` to `risk.BlackList`
* Update method signature to HasURL
* Update previous implemenations to match new method signature
* Update wired dependencies to include `risk.BlackList`
> Support malicious URL detection

- backend/app/adapter/gqlapi/resolver/authmutation.go
- backend/app/adapter/gqlapi/schema.go
> Implement viewChangeLog GraphQL API

- README.md
For setting up the project besides text-based instructions, there are also image-based instructions. The text-based instructions are clear enough to follow and having the images makes the Getting Started section very largely. 
Remove the images from that section.
> Remove images from Getting Started section

- README.md
- doc/sso/FACEBOOK.md
- doc/sso/GITHUB.md
https://github.com/short-d/short/issues/760
> Move Facebook & Github oauth config into separate files

- backend/app/adapter/sqldb/facebooksso.go
- backend/app/adapter/sqldb/facebooksso_integration_test.go
- backend/app/adapter/sqldb/githubsso.go
- backend/app/adapter/sqldb/githubsso_integration_test.go
- backend/app/adapter/sqldb/googlesso.go
- backend/app/adapter/sqldb/googlesso_integration_test.go
- backend/app/adapter/sqldb/table/facebooksso.go
- backend/app/adapter/sqldb/table/googlesso.go
- backend/app/usecase/repository/ssomap.go
- backend/app/usecase/repository/ssomap_fake.go
They are needed for email to ID migration in the following PRs.
> Add Google & Facebook SSO repository

- backend/app/adapter/sqldb/user.go
- backend/app/adapter/sqldb/user_integration_test.go
- backend/app/usecase/repository/user.go
- backend/app/usecase/repository/user_fake.go
- backend/app/usecase/sso/linker.go
- backend/app/usecase/sso/linker_test.go
> Revert "Auto generate ID for existing accounts during account linking"

- backend/app/adapter/sqldb/migration/23_set_title_and_released_at_to_not_null_changelog.sql
title and released_at should be not null according to GraphQL API
> Add migration to set title and released_at to not null

- backend/app/adapter/sqldb/migration/23_set_title_and_released_at_to_not_null_changelog.sql
- backend/cmd/cmd.go
- backend/dep/wire.go
- backend/dep/wire_gen.go
- backend/go.mod
- backend/go.sum
- backend/tool/data.go
Previously we are migrating from email to user ID. However, after the first and the second DB migrations, we unfortunately lost the most recent user data and had to redo the migration.
Add ID migration tool so that we can re-perform the migration.
> Add ID migration tool

- backend/app/usecase/authorizer/authorizer.go
- backend/app/usecase/authorizer/rbac/permission/permission.go
- backend/app/usecase/authorizer/rbac/role/role.go
Part of #612 
Add admin view permission to various related user roles
> Add view admin panel permission to different user roles

- backend/app/adapter/sqldb/short_link.go
- backend/app/adapter/sqldb/short_link_integration_test.go
- backend/app/adapter/sqldb/table/short_link.go
- backend/app/adapter/sqldb/table/user_short_link.go
- backend/app/adapter/sqldb/user_short_link.go
- backend/app/adapter/sqldb/user_short_link_integration_test.go
Part of [#794](https://github.com/short-d/short/issues/794). I tried to rename more parts but then the PR became a way too large and it is harder to review.
> Rename tables in backend

- backend/app/adapter/sqldb/migration/26_add_meta_tags_to_url.sql
> Add meta tags to short_link table

- frontend/src/component/pages/AdminPage.scss
- frontend/src/component/styles/color.scss
- frontend/src/component/styles/layer.scss
- frontend/src/component/styles/shadow.scss
- frontend/src/component/ui/Drawer.scss
- frontend/src/component/ui/Navigation.scss
Admin panel color scheme has too much contrast.
Change admin panel background to light gray.
> Restyle admin panel

- frontend/src/service/ShortLinkGraphQL.api.ts
- frontend/src/service/Url.service.ts
> Rename URL to shortlink for GraphQL queries in client side

- backend/app/adapter/gqlapi/resolver/error.go
Part of #612 
Add unauthorized error type to return error response when user is trying to make an unauthorized action.
> Add new unauthorized error type

- backend/app/adapter/gqlapi/resolver/error.go
- backend/app/adapter/sqldb/changelog.go
- backend/app/adapter/sqldb/changelog_integration_test.go
- backend/app/usecase/repository/change_log.go
- backend/app/usecase/repository/change_log_fake.go
Part of #612 
Add update change logs function in sqldb adapter and change logs repository.
> Add update Change logs functionality in ChangeLogs Repo

- frontend/src/component/pages/shared/Footer.tsx
- frontend/src/component/styles/color.scss
- frontend/src/component/styles/shadow.scss
- frontend/src/component/ui/ChangeLogModal.scss
- frontend/src/component/ui/Modal.scss
- frontend/src/component/ui/ViewChangeLogButton.tsx
> Restyle changelog modal

- frontend/src/component/ui/ChangeLogModal.scss
> Restyle change log title

- backend/app/usecase/search/filter.go
- backend/app/usecase/search/filter_test.go
- backend/app/usecase/search/order/order.go
- backend/app/usecase/search/search.go
- backend/app/usecase/search/search_test.go
Fixes [issue #869](https://github.com/short-d/short/issues/869).
> Add constructor for Filter

- frontend/src/dep.ts
- frontend/src/service/Captcha.service.ts
- frontend/src/service/ShortLink.service.ts
- frontend/src/service/shortGraphQL/ShortLinkGraphQL.api.ts
- frontend/src/service/shortGraphQL/schema.ts
Integrate update short link API with frontend so that users can edit their short link through Web GUI.
> Integrate update short link API with frontend

- frontend/src/component/form/TextField.scss
- frontend/src/component/form/TextField.tsx
- frontend/src/component/pages/shared/CreateShortLinkSection.tsx
TextField is not keeping local state when text changes. This results in text field not responding to user's inputs.
> Keep local state for TextField and add default text

- frontend/src/component/ui/Icon.tsx
> Add edit and check icons

- frontend/src/component/pages/shared/ErrorModal.scss
Fix invalid reference to background color in ErrorModal.scss
> Fix invalid color reference in error modal

- frontend/src/service/ChangeLog.service.ts
- frontend/src/service/shortGraphQL/ChangeLogGraphQL.api.ts
- frontend/src/service/shortGraphQL/schema.ts
Part of #612 
Add get all changes client services to display all the available changes in the manage change logs section of admin panel.
> Add get all changes client services

- widget/emotic/src/component/Button.scss
- widget/emotic/src/component/Button.tsx
- widget/emotic/src/component/FeedbackModal.scss
- widget/emotic/src/component/FeedbackModal.tsx
- widget/emotic/src/component/Launcher.scss
- widget/emotic/src/component/Launcher.tsx
- widget/emotic/src/component/Promotion.scss
- widget/emotic/src/component/Promotion.tsx
- widget/emotic/src/component/tabs/CollectEmailTab.scss
- widget/emotic/src/component/tabs/CollectEmailTab.tsx
- widget/emotic/src/component/tabs/EmotionTab.scss
- widget/emotic/src/component/tabs/EmotionTab.tsx
- widget/emotic/src/component/tabs/ThankYouTab.scss
- widget/emotic/src/component/tabs/ThankYouTab.tsx
There is a chance to accidentally modify the styles of Emotic when embedding it on external site due to CSS naming conflicts.
Prefix all Emotic specific styles with `Emotic` to avoid styling leaking & conflicts.
> Append Emotic to all component styles to avoid style leaking

- widget/emotic/README.md
The example is using default placeholder, which is inconsistent with how developer should integrate Emotic.
Update README to reflect how to use Emotic.
> Update Emotic README

- frontend/src/service/Captcha.service.ts
- frontend/src/service/ChangeLog.service.ts
- frontend/src/service/shortGraphQL/ChangeLogGraphQL.api.ts
- frontend/src/service/shortGraphQL/schema.ts
Part of #612 
Add update change client service methods which allows authorized user to update existing changes.
> Add update change client service methods

- CONTRIBUTING.md
Previously, people were stressing out over standups. Many of them prefer very relaxing development pace.
Introduced the concepts of core team so that active contributors can together move the project forwards.
> Revise contributing guidance

- backend/app/usecase/shortlink/creator_test.go
- backend/app/usecase/shortlink/metatag_test.go
- backend/app/usecase/shortlink/retriever_test.go
This PR adds meaningful test cases that cover not covered code in the usecase/shortlink package.
> Add test cases for usecase/shortlink

- widget/emotic/README.md
This is no instruction on how to configure dev environment for Emotic widget.
Include dev scripts for Emotic widget.
> Add documentation on launching emotic dev server

- story/.storybook/main.js
- story/package.json
- story/src/0-Button.stories.module.scss
- story/src/0-Button.stories.tsx
- story/tsconfig.json
- story/yarn.lock
> Create story for button

- .drone.yml
- story/.dockerignore
- story/Dockerfile
- story/default.conf
- story/package.json
This will make storybook accessible on the Internet.
> Add continuous deployment for storybook

- .drone.yml
> Fix image spelling

- backend/app/adapter/sqldb/app_integration_test.go
- backend/app/adapter/sqldb/main_test.go
- backend/app/adapter/sqldb/short_link_integration_test.go
- backend/app/adapter/sqldb/user_changelog_integration_test.go
- backend/app/adapter/sqldb/user_integration_test.go
- backend/app/adapter/sqldb/user_short_link_integration_test.go
- backend/app/fw/must/time.go
- backend/app/fw/ptr/time.go
Fixes [issue #977](https://github.com/short-d/short/issues/977)
> Replace mustParseTime with must.Time across the codebase

- frontend/src/dep.ts
- frontend/src/service/GraphQLError.ts
- frontend/src/service/ShortLink.service.ts
- frontend/src/service/shortGraphQL/ShortLinkGraphQL.api.ts
This is for issue https://github.com/short-d/short/issues/599
Refactor invokeCreateShortLinkApi.
> Refactor invokeCreateShortLinkApi 

- frontend/src/component/pages/shared/CreateShortLinkSection.tsx
- frontend/src/component/pages/shared/ShortLinkUsage.tsx
- frontend/src/component/pages/shared/UserShortLinksSection.spec.tsx
- frontend/src/component/pages/shared/UserShortLinksSection.tsx
- frontend/src/component/ui/SearchBar.spec.tsx
- frontend/src/component/ui/SearchBar.tsx
- frontend/src/entity/ShortLink.tsx
- frontend/src/service/Search.service.ts
- frontend/src/service/ShortLink.service.ts
- frontend/src/service/shortGraphQL/ShortLinkGraphQL.api.ts
- frontend/src/state/reducers.ts
Second part and closes [issue #863](https://github.com/short-d/short/issues/863)
> Rename originalLink into longLink in client side components

- backend/app/adapter/routing/api.yml
- backend/app/adapter/sqldb/short_link.go
- backend/app/adapter/sqldb/short_link_integration_test.go
- backend/app/usecase/repository/shortlink.go
- backend/app/usecase/repository/shortlink_fake.go
This will merge in the last 2 PRs into production:
- https://github.com/short-d/short/pull/969
- https://github.com/short-d/short/pull/994
> Merge into prod: localhost api docs and delete-short-link feature

- story/src/2-Icon.stories.module.scss
- story/src/2-Icon.stories.tsx
> Add Icon story
